MINECRAFT_ROOT_DIR: /home/minecraft/server
MINECRAFT_DATA_DIR: "{{ MINECRAFT_ROOT_DIR }}/data"
MINECRAFT_SERVER_JAR_URL: https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar
MINECRAFT_SERVER_JAR: minecraft-server-1.13.2.jar
